controllers:
    dashboard:
        class: device.controllers.DashboardController
        template: src/main/resources/view/dashboard.fxml
        options:
            - main

    help_me:
        class: device.controllers.HelpMeController
        template: src/main/resources/view/help_me.fxml