parameters:
    symbiosis:
        host: "http://192.168.1.7"
        port: "9000"
        type: "device"
        event: "message"
        device_name: "Sphinx"
        email: "test@test.test"
    DHT22_pin: 7
