tasks:
    DHT22:
        class: tasks.DHT22Task
        rate: 5000
        arguments:
            - '@DHT22'

    symbiosis:
        class: tasks.SymbiosisTask
        rate: 5000
        arguments:
            - '@DHT22'
            - '%symbiosis%'

